on:
  release:
    types: [published]

name: release

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Build"
      uses: okteto/build@master
      env:
        COMMIT_SHA: ${{ github.sha }}
      with:
        tag: okteto/remote:${{ github.ref }}
        buildargs: COMMIT_SHA